import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { Aside } from "@/components/Aside";

const prompt = Prompt({
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
  style:"normal"

})

export const metadata: Metadata = {
  title: "Code Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body   className={prompt.className}>
        <div className="app-container">
          <Aside />
          {children}
        </div>
      </body>
    </html>
  );
}
